# Generated by Django 5.0.3 on 2024-03-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('freelance', models.BooleanField(default=False)),
                ('python', models.IntegerField()),
                ('django', models.IntegerField()),
                ('html', models.IntegerField()),
                ('css', models.IntegerField()),
                ('js', models.IntegerField()),
                ('github', models.IntegerField()),
                ('about', models.TextField()),
            ],
        ),
    ]
